version: "3"
services:
  database:
    image: "postgres"
    container_name: "db_image"

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sarapostgresql
      - POSTGRES_DB=Product
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

